// File generated by FlutterFire CLI.
// This is a minimal configuration for Firebase
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIJSZt3y5-inVatNUnrUmMlX2W48457K4',
    appId: '1:765895929379:android:c7986dbb47b105b557cb96',
    messagingSenderId: '765895929379',
    projectId: 'bhoomi-bb321',
    storageBucket: 'bhoomi-bb321.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'bhoomi-v1',
    storageBucket: 'bhoomi-v1.appspot.com',
    iosBundleId: 'com.example.bhoomiV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'bhoomi-v1',
    storageBucket: 'bhoomi-v1.appspot.com',
    iosBundleId: 'com.example.bhoomiV1',
  );

  // Linux configuration (for development/testing only)
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBxNQZQHq3-YOUR-ANDROID-API-KEY',
    appId: '1:123456789:android:YOUR_APP_ID',
    messagingSenderId: '123456789',
    projectId: 'bhoomi-v1',
    storageBucket: 'bhoomi-v1.appspot.com',
  );
}
